CREATE TABLE `ticket_transactions` (
    `ticket_id`          INT(20) UNSIGNED                                                                                      DEFAULT NULL,
    `ticket_crc`         VARCHAR(32)                                                                                           DEFAULT NULL,
    `FirstName`          VARCHAR(128)                                                                                          DEFAULT NULL,
    `LastName`           VARCHAR(128)                                                                                          DEFAULT NULL,
    `Address`            VARCHAR(255)                                                                                          DEFAULT NULL,
    `City`               VARCHAR(128)                                                                                          DEFAULT NULL,
    `Country`            VARCHAR(100)                                                                                          DEFAULT NULL,
    `State`              VARCHAR(25)                                                                                           DEFAULT NULL,
    `ZipCode`            VARCHAR(15)                                                                                           DEFAULT NULL,
    `Phone`              VARCHAR(60)                                                                                           DEFAULT NULL,
    `Email`              VARCHAR(255)                                                                                          DEFAULT NULL,
    `TransactionID`      VARCHAR(45)                                                                                           DEFAULT NULL,
    `Product`            VARCHAR(255)                                                                                          DEFAULT NULL,
    `SiteID`             VARCHAR(45)                                                                                           DEFAULT NULL,
    `PolicyID`           INT(8)                                                                                                DEFAULT '0',
    `Amount`             FLOAT(10, 6)                                                                                          DEFAULT NULL,
    `Currency`           VARCHAR(3)                                                                                            DEFAULT NULL,
    `Status`             INT(8)                                                                                                DEFAULT NULL,
    `rState`             INT(8)                                                                                                DEFAULT NULL,
    `Technical`          VARCHAR(255)                                                                                          DEFAULT NULL,
    `Message`            VARCHAR(255)                                                                                          DEFAULT NULL,
    `InternalStatus`     ENUM ('Required Missing','CRC Mismatch','Successful','Declined','Error','Pending','Scrubbed','Fraud') DEFAULT NULL,
    `CC_CCV`             VARCHAR(3)                                                                                            DEFAULT NULL,
    `CC_MD5_NUM`         VARCHAR(32)                                                                                           DEFAULT NULL,
    `CC_ExpiryMonth`     INT(3)                                                                                                DEFAULT NULL,
    `CC_ExpiryYear`      INT(3)                                                                                                DEFAULT NULL,
    `CC_Name`            VARCHAR(40)                                                                                           DEFAULT NULL,
    `CC_Type`            VARCHAR(20)                                                                                           DEFAULT NULL,
    `ECHECK_SSN`         VARCHAR(128)                                                                                          DEFAULT NULL,
    `ECHECK_ROUTING`     VARCHAR(128)                                                                                          DEFAULT NULL,
    `ECHECK_ACCOUNT_MD5` VARCHAR(32)                                                                                           DEFAULT NULL,
    `DateCreated`        TIMESTAMP NULL                                                                                        DEFAULT NULL,
    `TransMode`          ENUM ('Open','Closed','Refunded')                                                                     DEFAULT 'Open',
    `TransModeChanged`   DATETIME                                                                                              DEFAULT NULL
);


CREATE TABLE `tickets` (
    `ticket_id`                 INT(30) UNSIGNED NOT NULL AUTO_INCREMENT,
    `ticket_crc`                VARCHAR(32)                            DEFAULT NULL,
    `ticket_from_uid`           INT(20)                                DEFAULT '0',
    `ticket_to_uid`             INT(20)                                DEFAULT NULL,
    `ticket_created`            DATETIME                               DEFAULT NULL,
    `ticket_timestamp`          TIMESTAMP        NULL                  DEFAULT NULL,
    `ticket_closed`             DATETIME                               DEFAULT NULL,
    `ticket_ip`                 VARCHAR(25)                            DEFAULT NULL,
    `ticket_hostname`           VARCHAR(255)                           DEFAULT NULL,
    `ticket_currency`           VARCHAR(3)                             DEFAULT 'AUD',
    `ticket_totalvalue`         FLOAT(10, 6)                           DEFAULT '0.000000',
    `ticket_payment_made`       INT(2)                                 DEFAULT '0',
    `ticket_confirmed`          INT(2)                                 DEFAULT '0',
    `ticket_payment_type`       ENUM ('CC','DIRECTDEBIT','BPAY','EFT') DEFAULT 'CC',
    `ticket_trigger_url`        MEDIUMTEXT,
    `ticket_last_triggered`     DATETIME                               DEFAULT NULL,
    `ticket_trigger_recieptnum` VARCHAR(50)                            DEFAULT NULL,
    `ticket_return_url`         MEDIUMTEXT,
    `ticket_cancel_url`         MEDIUMTEXT,
    `ticket_payee_emailaddy`    VARCHAR(255)                           DEFAULT NULL,
    `ticket_intabill_siteid`    VARCHAR(40)                            DEFAULT NULL,
    `ticket_intabill_custom`    VARCHAR(255)                           DEFAULT NULL,
    `ticket_intabill_seed`      VARCHAR(255)                           DEFAULT NULL,
    `ticket_sessionid`          VARCHAR(32)                            DEFAULT NULL,
    `ticket_producttext`        VARCHAR(128)                           DEFAULT NULL,
    PRIMARY KEY (`ticket_id`)
);

CREATE TABLE `tickets_items` (
    `ticket_id`         INT(30) UNSIGNED DEFAULT NULL,
    `item_name`         VARCHAR(255)     DEFAULT NULL,
    `item_quanity`      VARCHAR(30)      DEFAULT NULL,
    `item_unitprice`    FLOAT(10, 4)     DEFAULT NULL,
    `item_currency`     VARCHAR(3)       DEFAULT 'AUD',
    `item_cateloguenum` VARCHAR(35)      DEFAULT 'SUNDRY'
);
